CREATE DATABASE IF NOT EXISTS bankdb;
USE bankdb;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  full_name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS accounts (
  acc_no INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  balance DOUBLE DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  acc_no INT NOT NULL,
  type VARCHAR(10),
  amount DOUBLE,
  description VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (acc_no) REFERENCES accounts(acc_no) ON DELETE CASCADE
);
